version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Change to your desired username
      RABBITMQ_DEFAULT_PASS: guest  # Change to your desired password
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data storage for RabbitMQ
volumes:
  rabbitmq_data:

  