# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import key_pb2 as cryptography_dot_asymmetric_dot_key__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cryptography/asymmetric/key_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class KeyStub(object):
    """*
    Service for cryptographic operations involving key pairs and signatures.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/evercore.idvalid.cryptography.asymmetric.Key/Generate',
                request_serializer=cryptography_dot_asymmetric_dot_key__pb2.GenerateRequest.SerializeToString,
                response_deserializer=cryptography_dot_asymmetric_dot_key__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Sign = channel.unary_unary(
                '/evercore.idvalid.cryptography.asymmetric.Key/Sign',
                request_serializer=cryptography_dot_asymmetric_dot_key__pb2.SignRequest.SerializeToString,
                response_deserializer=cryptography_dot_asymmetric_dot_key__pb2.SignResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/evercore.idvalid.cryptography.asymmetric.Key/Verify',
                request_serializer=cryptography_dot_asymmetric_dot_key__pb2.VerifyRequest.SerializeToString,
                response_deserializer=cryptography_dot_asymmetric_dot_key__pb2.VerifyResponse.FromString,
                _registered_method=True)


class KeyServicer(object):
    """*
    Service for cryptographic operations involving key pairs and signatures.
    """

    def Generate(self, request, context):
        """*
        Generates a key pair and optionally a signature.

        @param GenerateRequest The request message containing data and algorithm details.
        @return GenerateResponse The response message containing the generated key pair and signature.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """*
        Signs data using a private key.

        @param SignRequest The request message containing the private key, data, and optional algorithm.
        @return SignResponse The response message containing the generated signature.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """*
        Verifies a signature using a public key.

        @param VerifyRequest The request message containing the public key, data, signature, and optional algorithm.
        @return VerifyResponse The response message indicating whether the signature is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=cryptography_dot_asymmetric_dot_key__pb2.GenerateRequest.FromString,
                    response_serializer=cryptography_dot_asymmetric_dot_key__pb2.GenerateResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=cryptography_dot_asymmetric_dot_key__pb2.SignRequest.FromString,
                    response_serializer=cryptography_dot_asymmetric_dot_key__pb2.SignResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=cryptography_dot_asymmetric_dot_key__pb2.VerifyRequest.FromString,
                    response_serializer=cryptography_dot_asymmetric_dot_key__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evercore.idvalid.cryptography.asymmetric.Key', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evercore.idvalid.cryptography.asymmetric.Key', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Key(object):
    """*
    Service for cryptographic operations involving key pairs and signatures.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evercore.idvalid.cryptography.asymmetric.Key/Generate',
            cryptography_dot_asymmetric_dot_key__pb2.GenerateRequest.SerializeToString,
            cryptography_dot_asymmetric_dot_key__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evercore.idvalid.cryptography.asymmetric.Key/Sign',
            cryptography_dot_asymmetric_dot_key__pb2.SignRequest.SerializeToString,
            cryptography_dot_asymmetric_dot_key__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evercore.idvalid.cryptography.asymmetric.Key/Verify',
            cryptography_dot_asymmetric_dot_key__pb2.VerifyRequest.SerializeToString,
            cryptography_dot_asymmetric_dot_key__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
