# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authn/user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..models import authn_pb2 as models_dot_authn__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uthn/user.proto\x12\x11idvalid.rpc.authn\x1a\x12models/authn.proto\"8\n\rCreateRequest\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.idvalid.authn.CreateUser\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t2U\n\x04User\x12M\n\x06\x43reate\x12 .idvalid.rpc.authn.CreateRequest\x1a!.idvalid.rpc.authn.CreateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authn.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=59
  _globals['_CREATEREQUEST']._serialized_end=115
  _globals['_CREATERESPONSE']._serialized_start=117
  _globals['_CREATERESPONSE']._serialized_end=145
  _globals['_USER']._serialized_start=147
  _globals['_USER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
