# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serializer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10serializer.proto\x12\x1c\x65vercore.test.grpc.framework\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x05\n\rFieldTestData\x12\x15\n\rboolean_field\x18\x01 \x01(\x08\x12\x12\n\nchar_field\x18\x02 \x01(\t\x12\x13\n\x0b\x65mail_field\x18\x03 \x01(\t\x12\x13\n\x0bregex_field\x18\x04 \x01(\t\x12\x12\n\nslug_field\x18\x05 \x01(\t\x12\x11\n\turl_field\x18\x06 \x01(\t\x12\x12\n\nuuid_field\x18\x07 \x01(\x03\x12\x17\n\x0fipaddress_field\x18\x08 \x01(\t\x12\x15\n\rinteger_field\x18\t \x01(\x03\x12\x13\n\x0b\x66loat_field\x18\n \x01(\x02\x12\x15\n\rdecimal_field\x18\x0b \x01(\t\x12\x32\n\x0e\x64\x61tetime_field\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x0e\x64uration_field\x18\x0f \x01(\x0b\x32\x19.google.protobuf.Duration\x12H\n\x0c\x63hoice_field\x18\x10 \x01(\x0e\x32\x32.evercore.test.grpc.framework.FieldTestData.Choice\x12Q\n\x15multiple_choice_field\x18\x11 \x03(\x0e\x32\x32.evercore.test.grpc.framework.FieldTestData.Choice\x12\x12\n\nlist_field\x18\x12 \x03(\t\x12N\n\ndict_field\x18\x13 \x03(\x0b\x32:.evercore.test.grpc.framework.FieldTestData.DictFieldEntry\x1a\x30\n\x0e\x44ictFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\x06\x43hoice\x12\x16\n\x12\x43HOICE_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43HOICE_FIRST\x10\x01\x12\x11\n\rCHOICE_SECOND\x10\x02\x12\x10\n\x0c\x43HOICE_THIRD\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serializer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELDTESTDATA_DICTFIELDENTRY']._loaded_options = None
  _globals['_FIELDTESTDATA_DICTFIELDENTRY']._serialized_options = b'8\001'
  _globals['_FIELDTESTDATA']._serialized_start=116
  _globals['_FIELDTESTDATA']._serialized_end=866
  _globals['_FIELDTESTDATA_DICTFIELDENTRY']._serialized_start=729
  _globals['_FIELDTESTDATA_DICTFIELDENTRY']._serialized_end=777
  _globals['_FIELDTESTDATA_CHOICE']._serialized_start=779
  _globals['_FIELDTESTDATA_CHOICE']._serialized_end=866
# @@protoc_insertion_point(module_scope)
