from evercore.constants import GLOBAL_ID_LENGTH

OTP_PIN_LENGTH = 128
CODE_LENGTH = 128
REF_ID_LENGTH = GLOBAL_ID_LENGTH
DEVICE_ID_LENGTH = GLOBAL_ID_LENGTH
ISSUER_NAME_LENGTH = 64
RECIPIENT_TYPE_NAME_LENGTH = 64
USAGE_NAME_LENGTH = 64

OBJECT_ID_LENGTH = GLOBAL_ID_LENGTH
LOOKUP_ID_LENGTH = GLOBAL_ID_LENGTH
