# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/authn.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12models/authn.proto\x12\ridvalid.authn\"t\n\nCreateUser\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\naccount_id\x18\x05 \x01(\t\x12\x11\n\tclient_id\x18\x06 \x01(\t\"\x83\x01\n\x0cUserLoggedIn\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bplatform_id\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x12\n\nuser_agent\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\x04\x12\x12\n\nip_address\x18\x06 \x01(\t\"A\n\x08Platform\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05subid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\"]\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05subid\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x04\x12\x13\n\x0bplatform_id\x18\x04 \x01(\x04\x12\x11\n\tdevice_id\x18\x05 \x01(\t\"\\\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05subid\x18\x02 \x01(\t\x12\x11\n\tis_active\x18\x03 \x01(\x08\x12\x10\n\x08is_staff\x18\x04 \x01(\x08\x12\x14\n\x0cis_superuser\x18\x05 \x01(\x08\"4\n\x0eUserActiveFlag\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x11\n\tis_active\x18\x02 \x01(\x08\",\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\"Y\n\x07\x41\x63\x63ount\x12!\n\x04user\x18\x01 \x01(\x0b\x32\x13.idvalid.authn.User\x12+\n\x07profile\x18\x02 \x01(\x0b\x32\x1a.idvalid.authn.UserProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.authn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSER']._serialized_start=37
  _globals['_CREATEUSER']._serialized_end=153
  _globals['_USERLOGGEDIN']._serialized_start=156
  _globals['_USERLOGGEDIN']._serialized_end=287
  _globals['_PLATFORM']._serialized_start=289
  _globals['_PLATFORM']._serialized_end=354
  _globals['_SESSION']._serialized_start=356
  _globals['_SESSION']._serialized_end=449
  _globals['_USER']._serialized_start=451
  _globals['_USER']._serialized_end=543
  _globals['_USERACTIVEFLAG']._serialized_start=545
  _globals['_USERACTIVEFLAG']._serialized_end=597
  _globals['_USERPROFILE']._serialized_start=599
  _globals['_USERPROFILE']._serialized_end=643
  _globals['_ACCOUNT']._serialized_start=645
  _globals['_ACCOUNT']._serialized_end=734
# @@protoc_insertion_point(module_scope)
