# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/enrollment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17models/enrollment.proto\x12\x12idvalid.enrollment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n\x05\x45mail\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x15\n\ris_registered\x18\x03 \x01(\x08\x12\x33\n\x0fregistered_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa5\x01\n\nEnrollment\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x05\x65mail\x18\x02 \x01(\x0b\x32\x19.idvalid.enrollment.Email\x12\r\n\x05state\x18\x03 \x01(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\x12\x12\n\nuser_agent\x18\x05 \x01(\t\x12+\n\x07\x63reated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAIL']._serialized_start=81
  _globals['_EMAIL']._serialized_end=236
  _globals['_ENROLLMENT']._serialized_start=239
  _globals['_ENROLLMENT']._serialized_end=404
# @@protoc_insertion_point(module_scope)
