# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/otp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10models/otp.proto\x12\x0bidvalid.otp\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n\tCreateOtp\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\r\n\x05usage\x18\x02 \x01(\t\x12\x0e\n\x06ref_id\x18\x03 \x01(\t\x12#\n\x06method\x18\x04 \x01(\x0e\x32\x13.idvalid.otp.Method\x12\x11\n\tdevice_id\x18\x05 \x01(\t\x12\x12\n\nuser_agent\x18\x06 \x01(\t\x12+\n\x07\x65xpires\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\remail_address\x18\x08 \x01(\tH\x00\x12\x16\n\x0cphone_number\x18\t \x01(\tH\x00\x12\x11\n\x07user_id\x18\n \x01(\tH\x00\x12\x10\n\x08owner_id\x18\x0b \x01(\rB\x0b\n\trecipient\"\xef\x01\n\x03Otp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\t\x12\r\n\x05usage\x18\x03 \x01(\t\x12\x0e\n\x06ref_id\x18\x04 \x01(\t\x12+\n\x07\x65xpires\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05token\x18\x06 \x01(\t\x12\x0f\n\x07\x61pplied\x18\x07 \x01(\x08\x12\x30\n\x0c\x61pplied_time\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp*R\n\x06Method\x12\x0f\n\x0bMETHOD_MAIL\x10\x00\x12\x0e\n\nMETHOD_SMS\x10\x01\x12\x13\n\x0fMETHOD_WHATSAPP\x10\x02\x12\x12\n\x0eMETHOD_IDVALID\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.otp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METHOD']._serialized_start=592
  _globals['_METHOD']._serialized_end=674
  _globals['_CREATEOTP']._serialized_start=67
  _globals['_CREATEOTP']._serialized_end=348
  _globals['_OTP']._serialized_start=351
  _globals['_OTP']._serialized_end=590
# @@protoc_insertion_point(module_scope)
