# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/tenant.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13models/tenant.proto\x12\x0eidvalid.tenant\"D\n\x06Tenant\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05subid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\"l\n\nTenantUser\x12\x11\n\ttenant_id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x10\n\x08is_owner\x18\x03 \x01(\x08\x12\x15\n\ris_registered\x18\x04 \x01(\x08\x12\x11\n\tis_active\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENANT']._serialized_start=39
  _globals['_TENANT']._serialized_end=107
  _globals['_TENANTUSER']._serialized_start=109
  _globals['_TENANTUSER']._serialized_end=217
# @@protoc_insertion_point(module_scope)
