# Generated by Django 4.2.18 on 2025-04-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'policy', 'verbose_name_plural': 'policies'},
        ),
        migrations.AlterModelOptions(
            name='policypermission',
            options={'verbose_name': 'policy permission', 'verbose_name_plural': 'policy permissions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepolicy',
            options={'verbose_name': 'role policy', 'verbose_name_plural': 'role policies'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'user role', 'verbose_name_plural': 'user roles'},
        ),
        migrations.AlterField(
            model_name='module',
            name='codename',
            field=models.CharField(max_length=64, verbose_name='codename'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('service', 'codename')},
        ),
    ]
