# Generated by Django 4.2.18 on 2025-04-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_module_options_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=64, verbose_name='codename'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'codename')},
        ),
    ]
