# Generated by Django 4.2.18 on 2025-04-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_permission_codename_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='RoleUser',
        ),
        migrations.AlterModelOptions(
            name='roleuser',
            options={'verbose_name': 'role user', 'verbose_name_plural': 'role users'},
        ),
        migrations.AddField(
            model_name='policy',
            name='permissions',
            field=models.ManyToManyField(related_name='policies', through='rbac.PolicyPermission', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='policies',
            field=models.ManyToManyField(related_name='roles', through='rbac.RolePolicy', to='rbac.policy'),
        ),
        migrations.AlterUniqueTogether(
            name='roleuser',
            unique_together={('role', 'user')},
        ),
    ]
