# Generated by Django 4.2.18 on 2025-04-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_rename_userrole_roleuser_alter_roleuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='roles', through='rbac.RoleUser', to='rbac.user'),
        ),
    ]
