# Generated by Django 4.2.18 on 2025-04-29 10:08

from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_role_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('is_active', models.BooleanField(verbose_name='active flag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='owner status')),
                ('is_registered', models.BooleanField(default=False, verbose_name='registered status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.user', verbose_name='user')),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
