# Generated by Django 4.2.18 on 2025-04-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_tenant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rbac.tenant', verbose_name='tenant'),
            preserve_default=False,
        ),
    ]
