# Generated by Django 4.2.16 on 2025-01-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
