# Generated by Django 4.2.16 on 2025-01-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_remove_application_user_application_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='grant',
            name='user_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='user id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idtoken',
            name='user_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='user id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
