# Generated by Django 4.2.18 on 2025-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_remove_grant_user_remove_idtoken_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='user id'),
        ),
    ]
