# Generated by Django 4.2.18 on 2025-02-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_remove_accesstoken_user_accesstoken_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='user id')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='otp')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
