# Generated by Django 4.2.18 on 2025-02-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prompt_callback_url',
            field=models.URLField(blank=True, null=True, verbose_name='prompt callback url'),
        ),
    ]
