# Generated by Django 4.2.18 on 2025-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_promptrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptrequest',
            name='answer',
            field=models.TextField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=32, null=True, verbose_name='answer'),
        ),
    ]
