# Generated by Django 4.2.18 on 2025-04-23 08:22

from django.db import migrations, models
import idvalid_core.generators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('is_active', models.BooleanField(verbose_name='active flag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
