# Generated by Django 4.2.18 on 2025-04-24 17:26

from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active flag')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.user', verbose_name='created_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
