# Generated by Django 4.2.18 on 2025-04-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='owner status'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='registered status'),
        ),
    ]
