USER_USERNAME_MAX_LENGTH = 150
USER_NAME_MAX_LENGTH = 256

# profile
PROFILE_NAME_MAX_LENGTH = 256

PLATFORM_TYPE_MOBILE = "mobile"
PLATFORM_TYPE_DESKTOP = "desktop"
PLATFORM_TYPE_WEB = "web"
PLATFORM_TYPE_OTHER = "other"
