# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otp/code.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eotp/code.proto\x12\x14\x65vercore.idvalid.otp\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb3\x03\n\rCreateRequest\x12=\n\x05\x65mail\x18\x01 \x01(\x0b\x32,.evercore.idvalid.otp.CreateRequest.EmailOtpH\x00\x12\x39\n\x03sms\x18\x02 \x01(\x0b\x32*.evercore.idvalid.otp.CreateRequest.SmsOtpH\x00\x12\x39\n\x03\x61pp\x18\x03 \x01(\x0b\x32*.evercore.idvalid.otp.CreateRequest.AppOtpH\x00\x12-\n\nexpires_in\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\r\n\x05usage\x18\x05 \x01(\t\x12\x0e\n\x06issuer\x18\x06 \x01(\t\x12\x0e\n\x06ref_id\x18\x07 \x01(\t\x12\x15\n\x08suppress\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x11\n\tdevice_id\x18\t \x01(\t\x1a\x19\n\x08\x45mailOtp\x12\r\n\x05value\x18\x01 \x01(\t\x1a\x17\n\x06SmsOtp\x12\r\n\x05value\x18\x01 \x01(\t\x1a\x17\n\x06\x41ppOtp\x12\r\n\x05value\x18\x01 \x01(\tB\x0b\n\trecipientB\x0b\n\t_suppress\"V\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12+\n\x07\x65xpires\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1c\n\x0e\x43onfirmRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0f\x43onfirmResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb3\x01\n\x04\x43ode\x12S\n\x06\x43reate\x12#.evercore.idvalid.otp.CreateRequest\x1a$.evercore.idvalid.otp.CreateResponse\x12V\n\x07\x43onfirm\x12$.evercore.idvalid.otp.ConfirmRequest\x1a%.evercore.idvalid.otp.ConfirmResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp.code_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=106
  _globals['_CREATEREQUEST']._serialized_end=541
  _globals['_CREATEREQUEST_EMAILOTP']._serialized_start=440
  _globals['_CREATEREQUEST_EMAILOTP']._serialized_end=465
  _globals['_CREATEREQUEST_SMSOTP']._serialized_start=467
  _globals['_CREATEREQUEST_SMSOTP']._serialized_end=490
  _globals['_CREATEREQUEST_APPOTP']._serialized_start=492
  _globals['_CREATEREQUEST_APPOTP']._serialized_end=515
  _globals['_CREATERESPONSE']._serialized_start=543
  _globals['_CREATERESPONSE']._serialized_end=629
  _globals['_CONFIRMREQUEST']._serialized_start=631
  _globals['_CONFIRMREQUEST']._serialized_end=659
  _globals['_CONFIRMRESPONSE']._serialized_start=661
  _globals['_CONFIRMRESPONSE']._serialized_end=695
  _globals['_CODE']._serialized_start=698
  _globals['_CODE']._serialized_end=877
# @@protoc_insertion_point(module_scope)
