from evercore.constants import GLOBAL_ID_LENGTH


ACCOUNT_AUTH_ID = GLOBAL_ID_LENGTH
ACCOUNT_USERNAME_MAX_LENGTH = 150
ACCOUNT_NAME_MAX_LENGTH = 256

EMAIL_ID_LENGTH = GLOBAL_ID_LENGTH
ENROLLMENT_ID_LENGTH = GLOBAL_ID_LENGTH
ENROLLMENT_STATE_LENGTH = GLOBAL_ID_LENGTH
OTP_ID_LENGTH = GLOBAL_ID_LENGTH

DEVICE_ID_LENGTH = GLOBAL_ID_LENGTH
AUTH_ID_LENGTH = GLOBAL_ID_LENGTH
PROFILE_ID_LENGTH = GLOBAL_ID_LENGTH
