# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enrollment/enrollment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65nrollment/enrollment.proto\x12\x1b\x65vercore.idvalid.enrollment\"V\n\x0e\x43onfirmRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\nuser_agent\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"\"\n\x0f\x43onfirmResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x0fGetEmailRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"!\n\x10GetEmailResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t2\xdb\x01\n\nEnrollment\x12\x64\n\x07\x43onfirm\x12+.evercore.idvalid.enrollment.ConfirmRequest\x1a,.evercore.idvalid.enrollment.ConfirmResponse\x12g\n\x08GetEmail\x12,.evercore.idvalid.enrollment.GetEmailRequest\x1a-.evercore.idvalid.enrollment.GetEmailResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollment.enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIRMREQUEST']._serialized_start=60
  _globals['_CONFIRMREQUEST']._serialized_end=146
  _globals['_CONFIRMRESPONSE']._serialized_start=148
  _globals['_CONFIRMRESPONSE']._serialized_end=182
  _globals['_GETEMAILREQUEST']._serialized_start=184
  _globals['_GETEMAILREQUEST']._serialized_end=228
  _globals['_GETEMAILRESPONSE']._serialized_start=230
  _globals['_GETEMAILRESPONSE']._serialized_end=263
  _globals['_ENROLLMENT']._serialized_start=266
  _globals['_ENROLLMENT']._serialized_end=485
# @@protoc_insertion_point(module_scope)
