from idvalid_integration.tasks import constants


OTP_USAGE_ENROLLMENT = "email-enrollment"
OTP_USAGE_FORGET_PASSWORD = "forget-password"
OTP_USAGE_CHANGE_EMAIL = "change-email"


EXCHANGE_PUBLISHER = constants.EXCHANGE_PUBLISHER

QUEUE_CONSUME = "idvalid.authn.consume"

ROUTING_CONSUME_OTP_PUBLISH_ENROLLMENT = (
    f"{constants.ROUTING_OTP_PUBLISH_PREFIX}.{OTP_USAGE_ENROLLMENT}")
ROUTING_CONSUME_OTP_PUBLISH_FORGET_PASSWORD = (
    f"{constants.ROUTING_OTP_PUBLISH_PREFIX}.{OTP_USAGE_FORGET_PASSWORD}")
ROUTING_CONSUME_OTP_PUBLISH_CHANGE_EMAIL = (
    f"{constants.ROUTING_OTP_PUBLISH_PREFIX}.{OTP_USAGE_CHANGE_EMAIL}")
TASK_CONSUME_OTP_PUBLISH = constants.TASK_CONSUME_OTP_PUBLISH

TASK_CONSUME_DEVICE_DELETE = constants.TASK_CONSUME_DEVICE_DELETE

ROUTING_CONSUME_TENANT_PUBLISH = (
    f"{constants.ROUTING_TENANT_PUBLISH_PREFIX}")
TASK_CONSUME_TENANT_PUBLISH = constants.TASK_CONSUME_TENANT_PUBLISH
ROUTING_CONSUME_TENANT_USER_PUBLISH = (
    f"{constants.ROUTING_TENANT_USER_PUBLISH_PREFIX}")
TASK_CONSUME_TENANT_USER_PUBLISH = constants.TASK_CONSUME_TENANT_USER_PUBLISH
ROUTING_CONSUME_TENANT_USER_DELETE = (
    f"{constants.ROUTING_TENANT_USER_PUBLISH_PREFIX}.delete")
TASK_CONSUME_TENANT_USER_DELETE = constants.TASK_CONSUME_TENANT_USER_DELETE

ROUTING_CONSUME_RBAC_ROLE_USER_CREATE = (
    f"{constants.ROUTING_RBAC_ROLE_USER_PUBLISH_PREFIX}.create")
TASK_CONSUME_RBAC_ROLE_USER_CREATE = constants.TASK_CONSUME_RBAC_ROLE_USER_CREATE
ROUTING_CONSUME_RBAC_ROLE_USER_DELETE = (
    f"{constants.ROUTING_RBAC_ROLE_USER_PUBLISH_PREFIX}.delete")
TASK_CONSUME_RBAC_ROLE_USER_DELETE = constants.TASK_CONSUME_RBAC_ROLE_USER_DELETE


EXCHANGE = constants.EXCHANGE_AUTH

QUEUE_EXTERNAL = "idvalid.authn.external"
ROUTING_EXTERNAL = constants.ROUTING_AUTH_EXTERNAL
TASK_EXTERNAL_SESSION_REVOKE = constants.TASK_EXTERNAL_AUTH_SESSION_REVOKE

QUEUE_SIGNAL = "idvalid.authn.signal"
ROUTING_SIGNAL = "authn.signal"
TASK_SIGNAL_ENROLLMENT_POST_CREATE = "idvalid.authn.signal.enrollment.post_create"
TASK_SIGNAL_FORGET_PASSWORD_POST_CREATE = "idvalid.authn.signal.forget_password.post_create"
TASK_SIGNAL_CHANGE_EMAIL_POST_CREATE = "idvalid.authn.signal.change_email.post_create"
TASK_SIGNAL_USER_LOGGED_IN = "idvalid.authn.signal.user.logged_in"
TASK_SIGNAL_PLATFORM_POST_CREATE = "idvalid.authn.signal.platform.post_create"
TASK_SIGNAL_PLATFORM_POST_UPDATE = "idvalid.authn.signal.platform.post_update"
TASK_SIGNAL_PLATFORM_POST_DELETE = "idvalid.authn.signal.platform.post_delete"
TASK_SIGNAL_SESSION_POST_CREATE = "idvalid.authn.signal.session.post_create"
TASK_SIGNAL_SESSION_POST_DELETE = "idvalid.authn.signal.session.post_delete"
TASK_SIGNAL_EMAIL_OTP_POST_CHALLENGE_CREATE = "idvalid.authn.signal.email_otp.post_challenge_create"
TASK_SIGNAL_ACCOUNT_POST_CREATE = "idvalid.authn.signal.account.post_create"
TASK_SIGNAL_USER_POST_ACTIVE_FLAG_UPDATE = "idvalid.authn.signal.user.post_active_flag_update"
TASK_SIGNAL_PROFILE_POST_UPDATE = "idvalid.authn.signal.profile.post_update"
