SERVICE_CODENAME_MAX_LENGTH = 64
SERVICE_NAME_MAX_LENGTH = 128
MODULE_CODENAME_MAX_LENGTH = 64
MODULE_NAME_MAX_LENGTH = 128
PERMISSION_CODENAME_MAX_LENGTH = 64
PERMISSION_NAME_MAX_LENGTH = 128
POLICY_NAME_MAX_LENGTH = 128
ROLE_NAME_MAX_LENGTH = 128
