# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cryptography/dsa/keypair.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ryptography/dsa/keypair.proto\x12!evercore.idvalid.cryptography.dsa\"U\n\x04Pair\x12\x13\n\x0bprivate_key\x18\x01 \x01(\x0c\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x16\n\tsignature\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x42\x0c\n\n_signature\"\x8a\x01\n\x0fGenerateRequest\x12?\n\talgorithm\x18\x01 \x01(\x0e\x32,.evercore.idvalid.cryptography.dsa.Algorithm\x12\x11\n\x04size\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x42\x07\n\x05_sizeB\x07\n\x05_data\"I\n\x10GenerateResponse\x12\x35\n\x04pair\x18\x01 \x01(\x0b\x32\'.evercore.idvalid.cryptography.dsa.Pair\"q\n\x0bSignRequest\x12?\n\talgorithm\x18\x01 \x01(\x0e\x32,.evercore.idvalid.cryptography.dsa.Algorithm\x12\x13\n\x0bprivate_key\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"!\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\x0c\"\x85\x01\n\rVerifyRequest\x12?\n\talgorithm\x18\x01 \x01(\x0e\x32,.evercore.idvalid.cryptography.dsa.Algorithm\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"\x1f\n\x0eVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08*e\n\tAlgorithm\x12\x19\n\x15\x41LGORITHM_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41LGORITHM_ED25519\x10\x01\x12\x13\n\x0f\x41LGORITHM_ECDSA\x10\x02\x12\x11\n\rALGORITHM_RSA\x10\x03\x32\xd6\x02\n\x07KeyPair\x12s\n\x08Generate\x12\x32.evercore.idvalid.cryptography.dsa.GenerateRequest\x1a\x33.evercore.idvalid.cryptography.dsa.GenerateResponse\x12g\n\x04Sign\x12..evercore.idvalid.cryptography.dsa.SignRequest\x1a/.evercore.idvalid.cryptography.dsa.SignResponse\x12m\n\x06Verify\x12\x30.evercore.idvalid.cryptography.dsa.VerifyRequest\x1a\x31.evercore.idvalid.cryptography.dsa.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cryptography.dsa.keypair_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALGORITHM']._serialized_start=691
  _globals['_ALGORITHM']._serialized_end=792
  _globals['_PAIR']._serialized_start=69
  _globals['_PAIR']._serialized_end=154
  _globals['_GENERATEREQUEST']._serialized_start=157
  _globals['_GENERATEREQUEST']._serialized_end=295
  _globals['_GENERATERESPONSE']._serialized_start=297
  _globals['_GENERATERESPONSE']._serialized_end=370
  _globals['_SIGNREQUEST']._serialized_start=372
  _globals['_SIGNREQUEST']._serialized_end=485
  _globals['_SIGNRESPONSE']._serialized_start=487
  _globals['_SIGNRESPONSE']._serialized_end=520
  _globals['_VERIFYREQUEST']._serialized_start=523
  _globals['_VERIFYREQUEST']._serialized_end=656
  _globals['_VERIFYRESPONSE']._serialized_start=658
  _globals['_VERIFYRESPONSE']._serialized_end=689
  _globals['_KEYPAIR']._serialized_start=795
  _globals['_KEYPAIR']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
