# Generated by Django 4.2.14 on 2024-09-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='tp',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipient',
            name='contact',
            field=models.CharField(default=None, max_length=128, verbose_name='contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuer',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together={('type', 'contact')},
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='recipient',
        ),
    ]
