# Generated by Django 4.2.14 on 2024-09-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_rename_tp_recipient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active flag'),
        ),
        migrations.AddField(
            model_name='code',
            name='ref_id',
            field=models.CharField(default=None, max_length=64, verbose_name='ref id'),
            preserve_default=False,
        ),
    ]
