# Generated by Django 4.2.14 on 2024-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_code_is_active_code_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='code',
            name='replied',
        ),
        migrations.AddField(
            model_name='code',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='applied'),
        ),
        migrations.AddField(
            model_name='code',
            name='suppressed',
            field=models.BooleanField(default=False, verbose_name='suppressed'),
        ),
    ]
