# Generated by Django 4.2.14 on 2024-09-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_remove_code_is_active_remove_code_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='device id'),
        ),
    ]
