# Generated by Django 4.2.14 on 2024-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_code_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipienttype',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
    ]
