# Generated by Django 4.2.14 on 2024-10-08 16:42

from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_alter_recipienttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('recipient_type', models.PositiveSmallIntegerField(db_index=True, verbose_name='recipient type')),
                ('contact', models.CharField(max_length=128, verbose_name='contact')),
            ],
            options={
                'unique_together': {('recipient_type', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('object_id', models.CharField(max_length=64, verbose_name='object id')),
                ('usage', models.CharField(max_length=64, verbose_name='usage')),
                ('ref_id', models.CharField(db_index=True, max_length=64, verbose_name='ref id')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'Mail'), (1, 'SMS'), (2, 'Whatsapp'), (3, 'IDValid')], db_index=True, verbose_name='method')),
                ('device_id', models.CharField(max_length=64, verbose_name='device id')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('response_token', models.TextField(verbose_name='token')),
                ('pin', models.CharField(editable=False, max_length=128, null=True, verbose_name='pin')),
                ('applied', models.BooleanField(default=False, verbose_name='applied')),
                ('applied_time', models.DateTimeField(blank=True, null=True, verbose_name='applied time')),
                ('suppressed', models.BooleanField(default=False, verbose_name='suppressed')),
                ('suppressed_time', models.DateTimeField(blank=True, null=True, verbose_name='suppressed time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otp.recipient2', verbose_name='recipient')),
            ],
            options={
                'unique_together': {('object_id', 'usage')},
            },
        ),
    ]
