# Generated by Django 4.2.14 on 2024-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_recipient2_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipient2',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipient2',
            name='value',
            field=models.CharField(default=None, max_length=128, verbose_name='value'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recipient2',
            unique_together={('recipient_type', 'value')},
        ),
        migrations.RemoveField(
            model_name='recipient2',
            name='contact',
        ),
    ]
