# Generated by Django 4.2.14 on 2024-10-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_alter_recipient2_unique_together_recipient2_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='response_token',
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='token'),
        ),
    ]
