# Generated by Django 4.2.16 on 2024-11-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_remove_otp_response_token_otp_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='code',
        ),
        migrations.AlterUniqueTogether(
            name='recipient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='type',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Issuer',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
        migrations.DeleteModel(
            name='RecipientType',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
