# Generated by Django 4.2.16 on 2024-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0010_remove_history_code_alter_recipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient2',
            name='recipient_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Email Address'), (1, 'Phone Number'), (2, 'User ID')], db_index=True, verbose_name='recipient type'),
        ),
    ]
