# Generated by Django 4.2.16 on 2025-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0011_alter_recipient2_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='owner_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='owner id'),
        ),
    ]
