# Generated by Django 4.2.18 on 2025-03-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0012_otp_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='twilio_verification_sid',
            field=models.TextField(blank=True, null=True, verbose_name='twilio verification sid'),
        ),
    ]
