# Generated by Django 4.2.16 on 2024-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last login date to this device.', null=True, verbose_name='last login'),
        ),
    ]
