# Generated by Django 4.2.16 on 2025-01-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_devicehistory_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='session_id',
            field=models.PositiveBigIntegerField(default=1, verbose_name='session id'),
            preserve_default=False,
        ),
    ]
