# Generated by Django 4.2.16 on 2025-01-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_session_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user_id', 'platform', 'device_id')},
        ),
        migrations.AlterField(
            model_name='device',
            name='session_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='session id'),
        ),
    ]
