# Generated by Django 4.2.16 on 2025-01-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_device_unique_together_alter_device_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='platform_id',
        ),
    ]
