# Generated by Django 4.2.16 on 2025-01-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_device_last_login_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_login_ip_address',
            new_name='last_login_ip',
        ),
    ]
