# Generated by Django 4.2.14 on 2024-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=64, unique=True, verbose_name='enrollment id')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_registered', models.BooleanField(verbose_name='registered flag')),
            ],
        ),
    ]
