# Generated by Django 4.2.14 on 2024-10-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_enrollment_enrollment_id_enrollment_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='enrollment id'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='otp_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='otp id'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='user agent'),
        ),
    ]
