# Generated by Django 4.2.14 on 2024-10-15 02:00

import account.generators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_enrollment_enrollment_id_enrollment_otp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('address', models.EmailField(max_length=254, unique=True, verbose_name='address')),
                ('resend_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='resend_date')),
                ('is_registered', models.BooleanField(default=False, editable=False, verbose_name='registered flag')),
                ('registered_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='registered')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expires',
            field=models.DateTimeField(default=account.generators.generate_otp_expires, verbose_name='expired date'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='otp_token',
            field=models.TextField(blank=True, null=True, verbose_name='otp token'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='device_id',
            field=models.CharField(max_length=64, verbose_name='device id'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='otp_id',
            field=models.TextField(blank=True, null=True, verbose_name='otp id'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='state',
            field=models.CharField(max_length=128, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user_agent',
            field=models.TextField(verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='account.email', verbose_name='email'),
        ),
    ]
