# Generated by Django 4.2.14 on 2024-10-15 02:47

from django.db import migrations, models
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_email_remove_enrollment_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
    ]
