# Generated by Django 4.2.14 on 2024-10-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_enrollment_subid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='suppressed',
            field=models.BooleanField(default=False, verbose_name='suppressed flag'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='suppressed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='suppressed time'),
        ),
    ]
