# Generated by Django 4.2.14 on 2024-10-17 03:53

import account.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_enrollment_suppressed_enrollment_suppressed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.TextField(verbose_name='subid')),
                ('token', models.TextField(verbose_name='token')),
                ('expires', models.DateTimeField(default=account.generators.generate_otp_token_expires, verbose_name='expires')),
                ('applied', models.BooleanField(default=False, verbose_name='applied flag')),
                ('applied_time', models.DateTimeField(blank=True, null=True, verbose_name='applied time')),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='otp_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='otp_token',
        ),
    ]
