# Generated by Django 4.2.14 on 2024-10-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otptoken_remove_enrollment_otp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='otp_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.otptoken'),
        ),
    ]
