# Generated by Django 4.2.14 on 2024-10-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_enrollment_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='otp_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.otptoken', verbose_name='otp token'),
        ),
    ]
