# Generated by Django 4.2.14 on 2024-10-17 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_enrollment_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
    ]
