# Generated by Django 4.2.14 on 2024-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_otptoken_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='enrollment_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
    ]
