# Generated by Django 4.2.14 on 2024-10-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_account_auth_id_remove_account_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_id',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='auth id'),
            preserve_default=False,
        ),
    ]
