# Generated by Django 4.2.14 on 2024-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_id',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='enrollment id'),
            preserve_default=False,
        ),
    ]
