# Generated by Django 4.2.14 on 2024-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0004_accesstoken_application_refreshtoken_idtoken_grant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active flag'),
        ),
    ]
