# Generated by Django 4.2.14 on 2024-10-18 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0006_userapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollment_id',
        ),
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='account id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
    ]
