# Generated by Django 4.2.16 on 2024-10-29 17:35

import authn.models.totp_device
from django.db import migrations, models
import django.utils.timezone
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0007_remove_user_enrollment_id_user_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('secret', models.CharField(default=authn.models.totp_device.generate_secret, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, verbose_name='secret')),
                ('step', models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.', verbose_name='step')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime at which to begin counting steps.', verbose_name='start time')),
                ('digits', models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8)], default=6, help_text='The number of digits to expect in a token.', verbose_name='digits')),
                ('tolerance', models.PositiveSmallIntegerField(default=1, help_text='The number of time steps in the past or future to allow.', verbose_name='tolerance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
