# Generated by Django 4.2.16 on 2024-10-31 04:17

import authn.models.platform
import authn.models.totp_device
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0008_totpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='digits',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9)], default=6, help_text='The number of digits to expect in a token.', verbose_name='digits'),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='start_time',
            field=models.DateTimeField(default=authn.models.totp_device.generate_start_time, help_text='The datetime at which to begin counting steps.', verbose_name='start time'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('private_key_der', models.BinaryField(default=authn.models.platform.generate_private_key_der, verbose_name='private key der')),
                ('totp_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='authn.totpdevice', verbose_name='totp device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
