# Generated by Django 4.2.16 on 2024-10-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0009_alter_totpdevice_digits_alter_totpdevice_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
    ]
