# Generated by Django 4.2.16 on 2024-10-31 10:46

import authn.models.totp_device
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0010_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret',
            field=models.BinaryField(default=authn.models.totp_device.generate_secret, max_length=40, verbose_name='secret'),
        ),
    ]
