# Generated by Django 4.2.16 on 2024-11-06 04:03

import authn.models.platform
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0011_alter_totpdevice_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='salt',
            field=models.BinaryField(default=authn.models.platform.generate_salt, verbose_name='salt'),
        ),
    ]
