# Generated by Django 4.2.16 on 2024-11-11 03:25

import authn.generators
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0013_remove_application_user_remove_grant_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('address', models.EmailField(max_length=254, unique=True, verbose_name='address')),
                ('resend_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='resend_date')),
                ('is_registered', models.BooleanField(default=False, editable=False, verbose_name='registered flag')),
                ('registered_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='registered')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.TextField(verbose_name='subid')),
                ('token', models.TextField(verbose_name='token')),
                ('expires', models.DateTimeField(default=authn.generators.generate_enrollment_token_expires, verbose_name='expires')),
                ('applied', models.BooleanField(default=False, verbose_name='applied flag')),
                ('applied_time', models.DateTimeField(blank=True, null=True, verbose_name='applied time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('device_id', models.CharField(max_length=64, verbose_name='device id')),
                ('state', models.CharField(max_length=128, verbose_name='state')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('expires', models.DateTimeField(default=authn.generators.generate_enrollment_otp_expires, verbose_name='expired date')),
                ('suppressed', models.BooleanField(default=False, verbose_name='suppressed flag')),
                ('suppressed_time', models.DateTimeField(blank=True, null=True, verbose_name='suppressed time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authn.email', verbose_name='email')),
                ('otp_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authn.otptoken', verbose_name='otp token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
