# Generated by Django 4.2.16 on 2024-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0014_email_otptoken_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='account id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
    ]
