# Generated by Django 4.2.16 on 2024-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0017_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
