# Generated by Django 4.2.16 on 2024-11-28 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0018_totp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='confirmed',
            field=models.BooleanField(default=True, help_text='Is this device ready for use?', verbose_name='confirmed'),
        ),
        migrations.AddField(
            model_name='totp',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
