# Generated by Django 4.2.16 on 2024-11-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0019_totp_confirmed_totp_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Is this device ready for use?', verbose_name='confirmed'),
        ),
    ]
