# Generated by Django 4.2.16 on 2024-11-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0020_alter_totp_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='A date and time when this device was confirmed.', null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='totp',
            name='failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='failure count'),
        ),
        migrations.AlterField(
            model_name='totp',
            name='failure_timestamp',
            field=models.DateTimeField(blank=True, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='failure timestamp'),
        ),
    ]
