# Generated by Django 4.2.16 on 2024-11-29 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0021_totp_confirmed_at_alter_totp_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
        migrations.AddField(
            model_name='totp',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='disabled at'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.totp', verbose_name='totp'),
        ),
        migrations.AlterField(
            model_name='totp',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The creator of this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_totp_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
