# Generated by Django 4.2.16 on 2024-12-02 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0022_totp_disabled_totp_disabled_at_user_totp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('pin', models.CharField(max_length=128, verbose_name='pin')),
                ('failure_timestamp', models.DateTimeField(blank=True, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='failure timestamp')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='failure count')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='The most recent date and time this device was used.', null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this device was initially created in the system.', verbose_name='created at')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
                ('disabled_at', models.DateTimeField(blank=True, null=True, verbose_name='disabled at')),
                ('created_by', models.ForeignKey(blank=True, help_text='The creator of this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_code_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
