# Generated by Django 4.2.16 on 2024-12-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0023_securitycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.securitycode', verbose_name='security code'),
        ),
    ]
