# Generated by Django 4.2.16 on 2024-12-04 01:23

import authn.models.forget_password
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0024_user_security_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('device_id', models.CharField(max_length=64, verbose_name='device id')),
                ('state', models.CharField(max_length=128, verbose_name='state')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('expires', models.DateTimeField(default=authn.models.forget_password.default_otp_expires, verbose_name='expired date')),
                ('suppressed', models.BooleanField(default=False, verbose_name='suppressed flag')),
                ('suppressed_time', models.DateTimeField(blank=True, null=True, verbose_name='suppressed time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('otp_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authn.otptoken', verbose_name='otp token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forget_passwords', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
