# Generated by Django 4.2.16 on 2024-12-04 05:19

import authn.models.forget_password
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0025_forgetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_date', models.DateTimeField(default=authn.models.forget_password.default_otp_resend, editable=False, verbose_name='resend_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fp_state', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
