# Generated by Django 4.2.16 on 2024-12-04 07:17

import authn.models.forget_password
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0026_forgetpasswordstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswordstate',
            name='resend_date',
            field=models.DateTimeField(blank=True, default=authn.models.forget_password.default_otp_resend, editable=False, null=True, verbose_name='resend_date'),
        ),
    ]
