# Generated by Django 4.2.16 on 2024-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0027_alter_forgetpasswordstate_resend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='deleted_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time'),
        ),
        migrations.AddField(
            model_name='platform',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='deleted flag'),
        ),
    ]
