# Generated by Django 4.2.16 on 2024-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0028_platform_deleted_time_platform_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('other', 'Other')], default='web', max_length=32, verbose_name='platform type'),
        ),
    ]
