# Generated by Django 4.2.16 on 2025-01-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0030_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authn.platform', verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user', 'platform', 'device_id')},
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('not_before', models.DateTimeField(blank=True, null=True, verbose_name='not before')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('issuer', models.CharField(blank=True, max_length=128, null=True, verbose_name='issuer')),
                ('subject', models.CharField(max_length=64, verbose_name='subject')),
                ('audience', models.CharField(max_length=64, verbose_name='audience')),
                ('claims', models.JSONField(blank=True, null=True, verbose_name='claims')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='authn.session', verbose_name='session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='session',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated_time',
        ),
    ]
