# Generated by Django 4.2.16 on 2025-01-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0031_alter_session_unique_together_session_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='issuer',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='multi_factor_auth',
            field=models.BooleanField(default=False, verbose_name='multi factor authentication'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='multi_factor_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='multi factor expiration date'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='audience',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='subject',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='subject'),
        ),
    ]
