# Generated by Django 4.2.16 on 2025-01-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0032_remove_refreshtoken_issuer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='claims',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='multi_factor_ref',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='multi factor reference'),
        ),
    ]
