# Generated by Django 4.2.16 on 2025-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0033_remove_refreshtoken_claims_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='extra_claims',
            field=models.JSONField(blank=True, null=True, verbose_name='claims'),
        ),
    ]
