# Generated by Django 4.2.16 on 2025-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0034_refreshtoken_extra_claims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='extra_claims',
            field=models.JSONField(blank=True, null=True, verbose_name='extra claims'),
        ),
    ]
