# Generated by Django 4.2.16 on 2025-01-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0035_alter_refreshtoken_extra_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(blank=True, help_text='The human-readable name of this device.', max_length=64, null=True)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('pin', models.CharField(blank=True, max_length=128, null=True, verbose_name='pin')),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp of the moment of expiry of the saved token.', verbose_name='valid until')),
                ('email', models.EmailField(blank=True, help_text='Optional alternative email address to send tokens to', max_length=254, null=True, verbose_name='email')),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='throttling failure timestamp')),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='throttling failure count')),
                ('last_generated_timestamp', models.DateTimeField(blank=True, help_text='The last time a token was generated for this device.', null=True, verbose_name='last generated timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this device was initially created in the system.', null=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='The most recent date and time this device was used.', null=True, verbose_name='last used at')),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
