# Generated by Django 4.2.18 on 2025-03-06 07:34

import authn.models.two_fa.passkey
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0037_changeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('is_active', models.BooleanField(default=True, verbose_name='active flag')),
                ('credential_id', models.BinaryField(db_index=True, verbose_name='credential_id')),
                ('public_key', models.BinaryField(verbose_name='public key')),
                ('sign_count', models.PositiveIntegerField(verbose_name='sign count')),
                ('attestation_object', models.BinaryField(verbose_name='attestation object')),
                ('aaguid', models.CharField(max_length=36, verbose_name='aaguid')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='last_auth_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last auth time'),
        ),
        migrations.AddField(
            model_name='user',
            name='passkey_device_count',
            field=models.PositiveIntegerField(default=0, verbose_name='passkey device count'),
        ),
        migrations.CreateModel(
            name='PasskeyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('challenge', models.BinaryField(default=authn.models.two_fa.passkey.generate_challenge, max_length=64, verbose_name='challenge')),
                ('timeout', models.PositiveIntegerField(blank=True, null=True, verbose_name='timeout')),
                ('usage', models.CharField(choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=64, verbose_name='usage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('passkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='authn.passkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkey_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='passkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
