# Generated by Django 4.2.18 on 2025-03-13 04:56

import authn.models.two_fa.backup_code
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0038_passkey_session_last_auth_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True, verbose_name='throttling failure timestamp')),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.', verbose_name='throttling failure count')),
                ('last_generated_timestamp', models.DateTimeField(blank=True, help_text='The last time a token was generated for this device.', null=True, verbose_name='last generated timestamp')),
                ('codes', models.JSONField(default=authn.models.two_fa.backup_code.generate_codes, verbose_name='codes')),
                ('used_codes', models.JSONField(default=list, verbose_name='used codes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this device was initially created in the system.', null=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='The most recent date and time this device was used.', null=True, verbose_name='last used at')),
                ('created_by', models.ForeignKey(blank=True, help_text='The creator of this backup code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backup_code_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='backup_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.backupcode', verbose_name='backup code'),
        ),
    ]
