# Generated by Django 4.2.18 on 2025-03-19 06:40

from django.db import migrations, models
import idvalid_core.generators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0039_backupcode_user_backup_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone')),
                ('resend_date', models.DateTimeField(blank=True, null=True, verbose_name='resend date')),
                ('is_valid', models.BooleanField(default=False, verbose_name='valid flag')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
