# Generated by Django 4.2.18 on 2025-03-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0040_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authn.phone', verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authn.email', verbose_name='email'),
        ),
    ]
