# Generated by Django 4.2.18 on 2025-03-20 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0041_enrollment_phone_alter_enrollment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='phone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='is_registered',
            field=models.BooleanField(default=False, editable=False, verbose_name='registered flag'),
        ),
        migrations.AddField(
            model_name='phone',
            name='registered_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='registered'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='resend_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='resend date'),
        ),
    ]
