# Generated by Django 4.2.18 on 2025-04-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0042_remove_phone_created_at_remove_phone_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passkeychallenge',
            name='passkey',
        ),
        migrations.RemoveField(
            model_name='passkeychallenge',
            name='timeout',
        ),
        migrations.AlterField(
            model_name='passkey',
            name='credential_id',
            field=models.BinaryField(db_index=True, unique=True, verbose_name='credential_id'),
        ),
        migrations.AlterField(
            model_name='passkeychallenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passkey_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
