# Generated by Django 4.2.18 on 2025-04-16 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0043_remove_passkeychallenge_passkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='log', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='UserMFA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mfa', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('passkey_device_count', models.PositiveIntegerField(default=0, verbose_name='passkey device count')),
                ('backup_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.backupcode', verbose_name='backup code')),
                ('security_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.securitycode', verbose_name='security code')),
                ('totp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authn.totp', verbose_name='totp')),
            ],
        ),
    ]
