# Generated by Django 4.2.18 on 2025-04-22 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0044_userlog_userprofile_usermfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcode',
            name='last_generated_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The last time a token was generated for this device.', null=True, verbose_name='last generated timestamp'),
        ),
    ]
