# Generated by Django 4.2.18 on 2025-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0045_alter_backupcode_last_generated_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
    ]
