# Generated by Django 4.2.18 on 2025-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0046_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='admin_last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='admin last login'),
        ),
    ]
