# Generated by Django 4.2.18 on 2025-04-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0047_userlog_admin_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passkey_device_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='security_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp',
        ),
    ]
