# Generated by Django 4.2.18 on 2025-04-25 01:38

from django.db import migrations, models
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0048_remove_user_backup_code_remove_user_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_active', models.BooleanField(verbose_name='active flag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
