# Generated by Django 4.2.18 on 2025-04-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0049_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='name',
        ),
    ]
