# Generated by Django 4.2.18 on 2025-04-28 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0050_remove_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='owner status')),
                ('is_registered', models.BooleanField(default=False, verbose_name='registered status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authn.tenant', verbose_name='tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
