# Generated by Django 4.2.18 on 2025-04-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0051_tenantuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='date_joined',
        ),
    ]
