# Generated by Django 4.2.18 on 2025-04-29 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0052_remove_tenantuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='extra_related_claim_attrs',
            field=models.JSONField(blank=True, null=True, verbose_name='extra related claim attributes'),
        ),
        migrations.CreateModel(
            name='RTPluginTenant',
            fields=[
                ('refresh_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authn.refreshtoken', verbose_name='refresh token')),
                ('tenant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authn.tenantuser', verbose_name='tenant user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
