# Generated by Django 4.2.18 on 2025-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0053_refreshtoken_extra_related_claim_attrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='extra_related_claim_attrs',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='plugins',
            field=models.JSONField(blank=True, null=True, verbose_name='plugin in '),
        ),
    ]
