# Generated by Django 4.2.18 on 2025-04-29 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0054_remove_refreshtoken_extra_related_claim_attrs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.PositiveBigIntegerField(verbose_name='tenant id')),
                ('role_id', models.PositiveBigIntegerField(verbose_name='role id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('tenant_id', 'role_id', 'user')},
            },
        ),
    ]
