# Generated by Django 4.2.18 on 2025-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0056_session_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='mobile_logged_in_count',
            field=models.PositiveIntegerField(default=0, verbose_name='mobile logged in count'),
        ),
    ]
