# Generated by Django 4.2.18 on 2025-05-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0059_mobileotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='state',
            field=models.BinaryField(blank=True, max_length=32, null=True),
        ),
    ]
