# Generated by Django 4.2.18 on 2025-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0060_mobileotp_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted status'),
        ),
        migrations.AddField(
            model_name='mobileotp',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed status'),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='state',
            field=models.BinaryField(blank=True, max_length=32, null=True, verbose_name='state'),
        ),
    ]
