# Generated by Django 4.2.14 on 2024-09-12 01:53

from django.db import migrations, models
import django.utils.timezone
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_otp_id',
            field=models.CharField(default=None, editable=False, max_length=64, unique=True, verbose_name='last otp id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_otp_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last otp sent date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subid',
            field=models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_registered',
            field=models.BooleanField(default=False, editable=False, verbose_name='registered flag'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_otp_expiration',
            field=models.DateTimeField(editable=False, verbose_name='last otp expiration date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='registered_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='registered'),
        ),
    ]
