# Generated by Django 4.2.14 on 2024-09-12 02:00

from django.db import migrations, models
import django.db.models.deletion
import idvalid_core.generators


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_enrollment_last_otp_id_enrollment_last_otp_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.CharField(blank=True, db_column='subid', default=idvalid_core.generators.default_subid_generator, editable=False, help_text='Primary key shown to user.', max_length=64, null=True, unique=True, verbose_name='subid')),
                ('device_id', models.CharField(max_length=64, verbose_name='device id')),
                ('state', models.CharField(max_length=64)),
                ('user_agent', models.CharField(max_length=512, verbose_name='user agent')),
                ('otp_id', models.CharField(max_length=64, verbose_name='otp id')),
                ('expires', models.DateTimeField(verbose_name='expired date')),
                ('is_confirmed', models.BooleanField(default=False, editable=False, verbose_name='confirmed flag')),
                ('confirmed_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='confirmed date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_set', to='enrollment.enrollment', verbose_name='enrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
