# Generated by Django 4.2.14 on 2024-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_remove_enrollment_last_otp_expiration_otp_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='state',
            field=models.CharField(max_length=128, verbose_name='state'),
        ),
    ]
