# Generated by Django 4.2.14 on 2024-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='otp_id',
            field=models.TextField(blank=True, null=True, verbose_name='otp id'),
        ),
        migrations.AddField(
            model_name='code',
            name='otp_token',
            field=models.TextField(blank=True, null=True, verbose_name='otp token'),
        ),
    ]
