from evercore.constants import GLOBAL_ID_LENGTH


ENROLLMENT_ID_LENGTH = GLOBAL_ID_LENGTH
USER_ACCOUNT_ID_MAX_LENGTH = GLOBAL_ID_LENGTH
USER_USERNAME_MAX_LENGTH = 150
USER_NAME_MAX_LENGTH = 256
DEVICE_ID_LENGTH = GLOBAL_ID_LENGTH
ENROLLMENT_STATE_LENGTH = GLOBAL_ID_LENGTH
FORGET_PASSWORD_STATE_LENGTH = GLOBAL_ID_LENGTH
CHANGE_EMAIL_STATE_LENGTH = GLOBAL_ID_LENGTH


# Auth Refresh Token
RS256_ALGORITHM = "RS256"
HS256_ALGORITHM = "HS256"
ALGORITHM_TYPES = (
    (RS256_ALGORITHM, "RSA with SHA-2 256"),
    (HS256_ALGORITHM, "HMAC with SHA-2 256"),
)

JWT_ISSUER_CLAIM = "iss"
JWT_SUBJECT_CLAIM = "sub"
JWT_AUDIENCE = "aud"
JWT_EXPIRATION_CLAIM = "exp"
JWT_NOT_BEFORE_CLAIM = "nbf"
JWT_ISSUED_AT_CLAIM = "iat"
JWT_ID_CLAIM = "jti"
JWT_TOKEN_TYPE_CLAIM = "tty"
JWT_REFRESH_ID_CLAIM = "rti"
JWT_MF_AUTH_CLAIM = "mfa"
JWT_MF_EXPIRATION_CLAIM = "mfe"

JWT_ACCESS_TOKEN_TYPE = "access"
JWT_REFRESH_TOKEN_TYPE = "refresh"
